import { DashboardLayout } from "@/components/DashboardLayout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

import { useEffect, useState } from "react";
import { getRadiologyResults } from "@/services/api"; // Import our new API function
import DicomViewer from "@/components/DicomViewer";

import { jsPDF } from "jspdf";

const RadiologyResults = () => {
  const handleDownloadPDF = (report) => {
    const doc = new jsPDF();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text("Radiology Report", 105, 20, { align: "center" });

    // Patient Info
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text(`Patient Name: ${report.patientName || report.patient_name || 'Unknown'}`, 20, 40);
    doc.text(`Date: ${new Date(report.created_at || Date.now()).toLocaleDateString()}`, 20, 50);
    doc.text(`Report Type: ${report.report_type || 'General'}`, 20, 60);

    // Content
    let yPos = 80;

    if (report.findings) {
      doc.setFontSize(14);
      doc.text("Findings:", 20, yPos);
      yPos += 10;
      doc.setFontSize(11);
      const splitFindings = doc.splitTextToSize(report.findings, 170);
      doc.text(splitFindings, 20, yPos);
      yPos += splitFindings.length * 7 + 10;
    }

    if (report.impression) {
      doc.setFontSize(14);
      doc.text("Impression:", 20, yPos);
      yPos += 10;
      doc.setFontSize(11);
      const splitImpression = doc.splitTextToSize(report.impression, 170);
      doc.text(splitImpression, 20, yPos);
      yPos += splitImpression.length * 7 + 10;
    }

    if (report.recommendation) {
      doc.setFontSize(14);
      doc.text("Recommendation:", 20, yPos);
      yPos += 10;
      doc.setFontSize(11);
      const splitRec = doc.splitTextToSize(report.recommendation, 170);
      doc.text(splitRec, 20, yPos);
    }

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by AI-Powered Radiology Workflow", 105, 280, { align: "center" });

    doc.save(`${report.patientName || report.patient_name || 'patient'}_radiology_report.pdf`);
  };
  // State to store results, loading status, and errors
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  const [selectedScanId, setSelectedScanId] = useState(null);

  // useEffect to fetch data when the component mounts
  useEffect(() => {
    const fetchResults = async () => {
      try {
        setLoading(true);
        const data = await getRadiologyResults();
        setResults(data);
        console.log("RADIOLOGY RESULTS FROM BACKEND:", data);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };
    fetchResults();
  }, []); // The empty dependency array means this effect runs once on mount

  if (loading) {
    return (
      <DashboardLayout title="Radiology Results">
        <p>Loading results...</p>
      </DashboardLayout>
    );
  }

  if (error) {
    return (
      <DashboardLayout title="Radiology Results">
        <p className="text-red-500">Error: {error}</p>
      </DashboardLayout>
    );
  }

  return (
    <DashboardLayout title="Radiology Results">
      <div className="grid gap-6">
        {results.length === 0 ? (
          <Card className="border border-slate-200 bg-slate-50">
            <CardContent className="flex flex-col items-center justify-center py-10 px-8">
              <div className="text-center space-y-3">
                <div className="w-14 h-14 bg-slate-200 rounded-full flex items-center justify-center mx-auto">
                  <svg className="w-6 h-6 text-slate-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-base font-semibold text-slate-700">No Reports Available</h3>
                  <p className="text-sm text-slate-500 mt-1">Results will display here once they are ready.</p>
                </div>
              </div>
            </CardContent>
          </Card>
        ) : (
          results.map((result) => (
            <Card key={result.id || result._id}>
              <CardHeader>
                <div className="flex items-start justify-between">
                  <div>
                    <CardTitle>
                      {result.type === 'ml_generated' ? result.report_type : (result.testType || result.scanType || 'Radiology Report')}
                    </CardTitle>
                    <CardDescription>
                      <strong>Patient:</strong> {result.patientName || result.patient_name || 'Unknown'}
                      {result.patient_age && ` • Age: ${result.patient_age}`}
                      {result.patient_gender && ` • ${result.patient_gender}`}
                    </CardDescription>
                    <CardDescription className="text-xs mt-1">
                      {result.created_at ? new Date(result.created_at).toLocaleDateString() : result.date} •
                      {result.ml_model ? ` ML Model: ${result.ml_model}` : ` ${result.radiologist || 'Radiologist'}`}
                    </CardDescription>
                  </div>
                  <div className="flex flex-col gap-2">
                    <Badge variant={result.status_display === 'Completed' ? 'default' : 'secondary'}>
                      {result.status_display || result.status}
                    </Badge>
                    {result.type === 'ml_generated' && result.confidence_score && (
                      <Badge variant="outline" className="text-xs">
                        Confidence: {(result.confidence_score * 100).toFixed(1)}%
                      </Badge>
                    )}
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  <p className="text-sm text-gray-600">{result.status_description}</p>
                  {result.findings && (
                    <div>
                      <h4 className="font-medium text-sm">Findings:</h4>
                      <p className="text-foreground">{result.findings}</p>
                    </div>
                  )}
                  {result.impression && (
                    <div>
                      <h4 className="font-medium text-sm">Impression:</h4>
                      <p className="text-foreground">{result.impression}</p>
                    </div>
                  )}
                  {result.recommendation && (
                    <div>
                      <h4 className="font-medium text-sm">Recommendation:</h4>
                      <p className="text-foreground">{result.recommendation}</p>
                    </div>
                  )}
                  {!result.findings && !result.impression && !result.recommendation && (result.result || result.notes) && (
                    <div>
                      <h4 className="font-medium text-sm">Result:</h4>
                      <p className="text-foreground">{result.result || result.notes}</p>
                    </div>
                  )}
                  {result.notes && result.result && (
                    <div>
                      <h4 className="font-medium text-sm">Notes:</h4>
                      <p className="text-foreground text-sm text-muted-foreground">{result.notes}</p>
                    </div>
                  )}
                </div>
                <div className="flex gap-2">
                  <div className="flex gap-2">
                    {(() => {
                      // Logic to get Scan ID: 1. From database field, 2. From report_data JSON, 3. Regex from findings text
                      const scanId = result.scanId ||
                        result.report_data?.scan_id ||
                        (result.findings?.match(/Scan ID: (DICOM_\w+)/) || [])[1];

                      return scanId ? (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => setSelectedScanId(scanId)}
                        >
                          👁️ View Scan
                        </Button>
                      ) : null;
                    })()}
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => handleDownloadPDF(result)}
                    >
                      ⬇️ Download Report
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))
        )}
      </div>

      {/* DICOM Viewer Modal */}
      {selectedScanId && (
        <DicomViewer
          scanId={selectedScanId}
          onClose={() => setSelectedScanId(null)}
        />
      )}
    </DashboardLayout>
  );
};

export default RadiologyResults;
